/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#2f3131",
        "on-surface": "var(--color-on-surface)",
        "on-error-container": "#ffdad6",
        "brand-accent": "var(--color-brand-accent)",
        "on-primary-container": "#556d00",
        "pure-white": "var(--color-pure-white)",
        "surface-dim": "var(--color-surface-dim)",
        "on-secondary-fixed": "#1b1b1f",
        "on-tertiary-fixed": "#1a1c1c",
        "error": "#ffb4ab",
        "secondary-container": "#47464b",
        "secondary-fixed-dim": "#c8c5cb",
        "on-tertiary-container": "#636565",
        "secondary-fixed": "#e4e1e7",
        "inverse-on-surface": "#313032",
        "on-primary": "var(--color-on-primary)",
        "surface": "var(--color-surface)",
        "on-secondary-fixed-variant": "#47464b",
        "inverse-surface": "#e5e1e4",
        "tertiary": "var(--color-pure-white)",
        "on-primary-fixed-variant": "#3c4d00",
        "on-error": "#690005",
        "secondary": "var(--color-secondary)",
        "error-container": "#93000a",
        "outline-variant": "#444933",
        "surface-bright": "var(--color-surface-bright)",
        "surface-variant": "var(--color-surface-variant)",
        "outline": "var(--color-outline)",
        "inverse-primary": "#506600",
        "primary-container": "#c3f400",
        "background": "var(--color-background)",
        "on-primary-fixed": "#161e00",
        "alert-red": "#CF2929",
        "primary-fixed": "#c3f400",
        "tertiary-container": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-tint": "#abd600",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary": "var(--color-primary)",
        "on-background": "var(--color-on-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "structure-gray": "var(--color-structure-gray)",
        "surface-container-high": "var(--color-surface-container-high)",
        "tertiary-fixed": "#e2e2e2",
        "void-black": "var(--color-void-black)",
        "primary-fixed-dim": "#abd600",
        "on-secondary-container": "#b6b4b9",
        "on-tertiary-fixed-variant": "#454747",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container": "var(--color-surface-container)"
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "unit": "4px",
        "gutter": "1px",
        "stack-lg": "64px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "margin-mobile": "16px",
        "container-max": "1440px"
      },
      fontFamily: {
        "display-xl": ["Syne", "sans-serif"],
        "label-caps": ["Archivo Narrow", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "mono-ui": ["Archivo Narrow", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "subheading": ["Archivo Narrow", "sans-serif"],
        "headline-lg-mobile": ["Syne", "sans-serif"],
        "display-lg": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"]
      },
      fontSize: {
        'display-xl': ['96px', { lineHeight: '100%', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-lg': ['64px', { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '120%', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '120%', fontWeight: '700' }],
        'subheading': ['18px', { lineHeight: '140%', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '160%', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '160%', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '100%', letterSpacing: '0.1em', fontWeight: '500' }],
        'mono-ui': ['14px', { lineHeight: '120%', fontWeight: '400' }],
      }
    },
  },
  plugins: [],
}
